- name: Get latest release version of Espanso from GitHub
  github_release:
    user: federico-terzi
    repo: espanso
    action: latest_release
  register: espanso_release

- name: Install Espanso .deb package from Github.
  apt:
    deb: https://github.com/federico-terzi/espanso/releases/download/{{espanso_release.tag}}/gh_{{espanso_version}}_linux_amd64.deb
  when: espanso_release.changed

  https://github.com/federico-terzi/espanso/releases/download/v0.5.5/espanso-debian-amd64.deb