- name: Add /etc/default/cpufrequtils File
  file:
    path: /etc/default/cpufrequtils
    state: touch
    owner: root
    group: root
    mode: 0644
- name: Set CPU GOVERNOR to performance
  lineinfile:
    path: /etc/default/cpufrequtils
    line: 'GOVERNOR="performance"'
- name: Stop service ondemand, if started - Settinbg CPU to perf permanently
  service:
    name: ondemand
    state: stopped
- name: Disable service ondemand
  service:
    name: ondemand
    enabled: no
