# https://github.com/ansible/ansible/issues/50272
# - name: get my user id for user scoped systemd
#   become: true
#   become_user: "{{ myusername }}"
#   command: id -u
#   register: myuid

- name: Enable and Start System Scoped Services
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
      - ssh
      - docker

# https://github.com/ansible/ansible/issues/50272
# - name: Enable and Start User Scoped Services
#   become: true
#   become_user: "{{ myusername }}"
#   systemd:
#     # daemon_reload: yes
#     scope: user
#     enabled: yes
#     state: started
#     name: "{{ item }}"
#   environment:
#         XDG_RUNTIME_DIR: "/run/user/{{ myuid.stdout }}"
#   with_items:
#       - syncthing
#   register: result

# - debug: msg="{{ result }}"