- name: Enable SSH Server
  systemd:
    enabled: yes
    name: ssh
- name: Making Sure SSH is Started
  systemd:
    state: started
    name: ssh

- name: Enable Docker Service
  systemd:
    enabled: yes
    name: docker
- name: Making Sure SSH is Started
  systemd:
    state: started
    name: docker