- name: Enable SSH Server
  systemd:
    enabled: yes
    name: ssh
- name: Making Sure SSH is Started
  systemd:
    state: started
    name: ssh

- name: Enable Docker Service
  systemd:
    enabled: yes
    name: docker
- name: Making Sure Docker is Started
  systemd:
    state: started
    name: docker

# https://github.com/ansible/ansible/issues/50272
- name: get my user id for user scoped systemd
  become: true
  become_user: "{{ myusername }}"
  command: id -u
  register: myuid
# https://github.com/ansible/ansible/issues/50272
- name: Enable Syncthing Service
  become: true
  become_user: "{{ myusername }}"
  systemd:
    scope: user
    enabled: yes
    state: started
    name: syncthing
  environment:
        XDG_RUNTIME_DIR: "/run/user/{{ myuid.stdout }}"