- name: Enable SSH Server
  systemd:
    enabled: yes
    name: ssh
- name: Making Sure SSH is Started
  systemd:
    state: started
    name: ssh

- name: Enable Docker Service
  systemd:
    enabled: yes
    name: docker
- name: Making Sure Docker is Started
  systemd:
    state: started
    name: docker

- name: Enable Syncthing Service
  systemd:
    scope: user
    enabled: syncthing
    name: docker
- name: Making Sure Syncthing is Started
  systemd:
    scope: user
    state: started
    name: syncthing