- name: Enable and Start System Scoped Services
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
      - ssh
      - docker

# - name: Enable Systemd User Scoped Services
#   command: systemctl enable "{{item}}"@"{{ myusername }}"
#   with_items:
#       - syncthing

# - name: Start Systemd User Scoped Services
#   command: systemctl start "{{item}}"@"{{ myusername }}"
#   with_items:
#       - syncthing



- name: Enable and Start User Scoped Services
  systemd:
    enabled: yes
    state: started
    name: "{{ item }}"
  with_items:
      - "syncthing@{{ myusername }}"

# - debug: msg="{{ result }}"