- name: Placing ansible-pull-cron.sh
  copy:
    src: files/scripts/ansible-pull-cron.sh
    dest: "/usr/local/bin/ansible-pull-cron.sh"
    owner: root
    group: root
    mode: 0755

- name: Install Ansible Cron Job (40 Min)
  cron: user="dustin" name="Ansible provision" minute="*/40" job="/usr/local/bin/ansible-pull-cron.shl"

- name: Install Daily Ansible Cron Jobs
  cron: user="dustin" name="Ansible Daily provision" minute="30" hour="7,17" job="/usr/local/bin/ansible-pull-cron.sh"

- name: Add Ansible Cron Log
  file:
      path: /home/{{ myusername }}/.ansible-cron
      state: touch
      owner: root
      group: root
      mode: 0700

- name: Tap Ansible Cron Log #noqa 301
  shell: date >> /home/{{ myusername }}/.ansible-cron

- name: Rotate Ansible Cron Log #noqa 301
  shell: tail -n5 /home/{{ myusername }}/.ansible-cron > /home/{{ myusername }}/.ansible-cron.tmp && mv /home/{{ myusername }}/.ansible-cron.tmp /home/{{ myusername }}/.ansible-cron #noqa 204
