- name: Placing Uncrustify CFG
  copy:
    src: files/dotfiles/uncrustify/uncrustify.cfg
    dest: "/home/{{ myusername }}/.config/uncrustify.cfg"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing Ncspot CFG
  copy:
    src: files/dotfiles/ncspot/config.toml
    dest: "/home/{{ myusername }}/snap/ncspot/current/.config/ncspot/config.toml"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing Kitty CFG
  copy:
    src: files/dotfiles/kitty/kitty.conf
    dest: "/home/{{ myusername }}/.config/kitty/kitty.conf"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing Kitty Theme
  copy:
    src: files/dotfiles/kitty/snazzy.conf
    dest: "/home/{{ myusername }}/.config/kitty/snazzy.conf"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing .sbuildrc
  copy:
    src: files/dotfiles/sbuild/.sbuildrc
    dest: "/home/{{ myusername }}/.sbuildrc"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing .mk-sbuild.rc
  copy:
    src: files/dotfiles/sbuild/.mk-sbuild.rc
    dest: "/home/{{ myusername }}/.mk-sbuild.rc"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing nord.json tilix Theme
  copy:
    src: files/dotfiles/tilix/nord.json
    dest: "/usr/share/tilix/schemes/nord.json"
    owner: "root"
    group: "root"
    mode: 0644