- name: Placing .gitconfig dotfile
  copy:
    src: files/dotfiles/git/.gitconfig
    dest: "/home/{{ myusername }}/.gitconfig"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing .gitignore dotfile
  copy:
    src: files/dotfiles/git/.gitignore
    dest: "/home/{{ myusername }}/.gitignore"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing Uncrustify CFG
  copy:
    src: files/dotfiles/uncrustify/uncrustify.cfg
    dest: "/home/{{ myusername }}/.config/uncrustify.cfg"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing Ncspot CFG
  copy:
    src: files/dotfiles/ncspot/config.toml
    dest: "/home/{{ myusername }}/snap/ncspot/current/.config/ncspot/config.toml"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing .sbuildrc
  copy:
    src: files/dotfiles/sbuild/.sbuildrc
    dest: "/home/{{ myusername }}/.sbuildrc"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing .mk-sbuild.rc
  copy:
    src: files/dotfiles/sbuild/.mk-sbuild.rc
    dest: "/home/{{ myusername }}/.mk-sbuild.rc"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing .quiltrc
  copy:
    src: files/dotfiles/quilt/.quiltrc
    dest: "/home/{{ myusername }}/.quiltrc"
    owner: "{{ myusername }}"
    group: "{{ myusername }}"
    mode: 0700

- name: Placing nord.json tilix Theme
  copy:
    src: files/dotfiles/tilix/nord.json
    dest: "/usr/share/tilix/schemes/nord.json"
    owner: "root"
    group: "root"
    mode: 0644

- name: Placing Clockworks config
  copy:
    src: files/dotfiles/clockworks/clockdata
    dest: "/home/{{ myusername }}/.config/budgie-extras/clockworks/clockdata"
    owner: "root"
    group: "root"
    mode: 0644

- name: Placing panel.ini
  copy:
    src: files/dotfiles/budgie/panel.ini
    dest: "/etc/budgie-desktop/panel.ini"
    owner: "root"
    group: "root"