- name: Remove Desktop APT Packages
  apt:
    name: "{{ rempackages }}"
    state: absent
  vars:
    rempackages:
      - libreoffice-*
      - docker
      - docker-engine
      - docker.io
      - plank
      - geary
      - gnome-screenshot
      - code-insiders

- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
- name: Install Desktop APT Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - telegram-desktop
      - inxi
      - audacity
      - peek
      - neovim
      - xclip
      - ncdu
      - tmux
      - openssh-server
      - ubuntu-restricted-extras
      - debconf-utils
      - debhelper
      - ubuntu-dev-tools
      - piuparts
      - schroot
      - sbuild
      - lftp
      - htop
      - deluge-gtk
      - gnome-mpv
      - calibre
      - whois
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python-pip
      - nomacs
      - snapd-xdg-open
      - asciinema
      - flameshot
      - python-psutil
      - psutils
      - libimage-exiftool-perl
      - python3-pip
      - libcurl4
      - curl
      - gnupg-agent
      - font-manager
      - gnome-calculator
      - valac
      - uncrustify
      - devscripts
      - software-properties-gtk
      - meson
      - gnome-disk-utility
      - dlocate
      - ttf-mscorefonts-installer
      - fonts-emojione
      - ppa-purge
      - pylint
      - gtk-3-examples
      - libgtk-3-0
      - seafile-cli
      - dialog
      - pdfarranger
      - hub
      - rename
      - lazygit
      - encfs
      - graphviz
      - cpufrequtils
      - budgie-applications-menu
      - budgie-window-shuffler
      - pulseaudio
      - pavucontrol
      - nordvpn
      - gocryptfs
      - sirikali
      - insync
      - insync-nemo
      - preload

- name: Install ToDoist Desktop .deb package from Github.
  apt:
    deb: https://github.com/KryDos/todoist-linux/releases/download/1.19/Todoist_1.19.0_amd64.deb

- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
