- name: Remove Desktop APT Packages
  apt:
    name: "{{ rempackages }}"
    state: absent
  vars:
    rempackages:
      - libreoffice-*
      - plank
      - geary
      - gnome-screenshot
      - firefox

- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
- name: Install Desktop APT Packages
  apt:
    name: "{{ packages }}"
  vars:
    packages:
      - git
      - inxi
      - audacity
      - peek
      - xclip
      - ncdu
      - tmux
      - openssh-server
      - ubuntu-restricted-extras
      - debconf-utils
      - debhelper
      - ubuntu-dev-tools
      - piuparts
      - schroot
      - sbuild
      - lftp
      - htop
      - celluloid
      - gnome-firmware
      - drawing
      - calibre
      - whois
      - apt-transport-https
      - ca-certificates
      - software-properties-common
      - python3-pip
      - snapd-xdg-open
      - asciinema
      - flameshot
      - python-psutil
      - psutils
      - libimage-exiftool-perl
      - libcurl4
      - curl
      - gnupg-agent
      - font-manager
      - gnome-calculator
      - valac
      - uncrustify
      - libgtk-3-dev
      - devscripts
      - software-properties-gtk
      - meson
      - gnome-disk-utility
      - dlocate
      - ttf-mscorefonts-installer
      - fonts-emojione
      - ppa-purge
      - pylint
      - gtk-3-examples
      - libgtk-3-0
      - seafile-cli
      - dialog
      - pdfarranger
      - hub
      - rename
      - encfs
      - graphviz
      - cpufrequtils
      - budgie-applications-menu
      - budgie-window-shuffler
      - pulseaudio
      - pavucontrol
      - nordvpn
      - gocryptfs
      - sirikali
      # - insync
      # - insync-nemo
      - preload
      - jq
      - gnome-documents
      - brave-browser
      - budgie-clockworks-applet
      - typora
      - tailscale
      - mellowplayer

- name: Autoremove and Purge APT Packages
  apt:
    autoremove: yes
    purge: yes
