- name: Remove SNAP Packages
  snap:
    name: "{{ remsnaps }}"
    state: absent
  vars:
    remsnaps:
      - croc
      - polar-bookshelf

- name: Install Snap Packages
  snap:
    name:
      - spotify
      - hiri
      - lxd
      - ncspot
      - simplescreenrecorder
      - bitwarden
      - bw
      - icdiff
      - mumble
      - shfmt
      - review-tools
      - standard-notes
      - scrcpy
      - htmldoc
      - mailspring
      - libreoffice
      - ephemeral
      - glimpse-editor
      - gravit-designer
      - cheat
      - telegram-desktop
      - screen

- name: Install Classic Snap Packages
  snap:
    name: "{{ classicsnaps }}"
    classic: yes
  vars:
    classicsnaps:
      - go
      - restic
      - snapcraft
      - snapdiff
      - slack
      - code-insiders
      - espanso
      - kubectl

- name: Install Node Snap Package --channel=11/stable --classic
  snap:
    name: node
    channel: 13/stable
    classic: yes

- name: Install Multipass Snap Package --channel=beta --classic
  snap:
    name: multipass
    channel: beta
    classic: yes

- name: Install Snap Packages from --channel=edge
  snap:
    name: "{{edgesnaps}}"
    channel: edge
  vars:
    edgesnaps:
      - irccloud
      - authy

# - name: Install Snap Packages from --channel=beta
#   snap:
#     name: "{{betasnaps}}"
#     channel: beta
#   vars:
#     betasnaps:
#       - molecule

- name: Install Hugo Snap Package --channel=extended/edge
  snap:
    name: hugo
    channel: extended/edge
