- name: Install Snap Packages
  command: 'snap install "{{ item }}"'
  with_items:
    - irccloud
    - libreoffice
    - spotify
    - lxd
    - telegram-desktop
    - simplescreenrecorder
    - bitwarden
    - bw
    - serve
    - icdiff
    - mumble
    - typora-alanzanattadev
    - youtube-dl
    - shfmt
    - ffsend
    - pick-colour-picker
    - mailspring
- name: Install Classic Snap Packages
  command: 'snap install "{{ item }}" --classic'
  with_items:
    - go
    - restic
    - snapcraft
    - snapdiff
    - kubectl
    - code-insiders
    - slack

- name: Install Node Snap Package
  command: "snap install node --channel=11/stable --classic"

- name: Install Multipass Snap Package
  command: "snap install multipass --beta --classic"

- name: Install IRCCLOUD Desktop Snap Package
  command: "snap install irccloud --edge"

- name: Install Hugo Extended
  command: "snap install hugo --channel=extended/edge"
